### ISSUE TITLE
Running as root

### ISSUE THREAD

**Issue by BuxtonCalvin** [sowbug/mkeosimg#12]
I tried the latest version of the script on a ras pi with armbian os.

I get the following error:

![ERL](https://user-images.githubusercontent.com/23129738/208342023-420c844f-080e-400c-ac2c-02bebde12d79.png)

Also tried logging in as  a user and running with sudo but I get the same error message.

**Comment by sowbug** [comment]
Fixed. Please reopen if you're still seeing the same issue after updating to the latest.

**Comment by BuxtonCalvin** [comment]
All is good on creating the image.  No error messages.  However you may want to check the mkeosdrive script as it errors out when I run it-- gives various partition errors and warnings.

I used the standard linux commands to write the image so I'm good.  Thank  you for the quick fix and this absolutely necessary script.
