### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by enoch85** [sowbug/mkeosimg#5]
Internet is great! I'm so glad I found this! It saved me many hours of searching for solutions - not having a serial cable in stock.

Thank you very much for making this! :heart_eyes_cat:

**Comment by sowbug** [comment]
You're welcome! Sorry your router crapped out on you, and glad you were
able to get it fixed more easily.

**Comment by enoch85** [comment]
It's now public! https://www.techandme.se/bricked-edgerouter-poe/

**Comment by kipusoep** [comment]
Also a big thank you from me! This worked perfectly!
