### ISSUE TITLE
Possible To Use IMG File On Non-UBNT Hardware?

### ISSUE THREAD

**Issue by doughnet** [sowbug/mkeosimg#8]
I was curious if this is able to make a .img file that can boot (based on a firmware provided) then why would keep it from working on bare metal hardware or in virtualization (i.e. KVM/VMware)?

I did a quick test and it didn't work but curious if anyone else has tried and succeeded.

**Comment by sowbug** [comment]
It'd depend on whether the firmware's kernel supports the hardware
(physical or virtual) that you're running on. Since flash space is limited
on the Unifi hardware, I would be surprised if Ubiquiti included extra
hardware support.
